import "./sass/index.scss";
import applicationImage from "./assets/application_image.png";
import checkboxTick from "./sass/checkbox_tick.svg";
import closeIcon from "./assets/close_icon.svg";
import crmIcon from "./assets/crm_icon.png";
import emojiIcon from "./assets/emoji_icon.png";
import footerLogo from "./assets/footer_logo.svg";
import footerTgIcon from "./assets/footer_tg_icon.svg";
import footerWuIcon from "./assets/footer_wu_icon.svg";
import formImage1 from "./assets/form-image-1.png";
import formImage2 from "./assets/form-image-2.png";
import formImage3 from "./assets/form-image-3.png";
import formImage4 from "./assets/form-image-4.png";
import formImage5 from "./assets/form-image-5.png";
import goldBitrix from "./assets/gold_bitrix.png";
import headerLogoLaptop from "./assets/header__logo__laptop.svg";
import headerLogo from "./assets/header__logo.svg";
import integrationIcon from "./assets/integration_icon.png";
import liDecoration from "./assets/li_decoration.svg";
import mainImageDekstop from "./assets/main__image__dekstop.png";
import mainImageLaptop from "./assets/main__image__laptop.png";
import mainImage from "./assets/main__image.png";
import marketIcon from "./assets/market_icon.png";
import menuIcon from "./assets/menu_icon.svg";
import phoneCall from "./assets/phone-call.svg";
import sertif1 from "./assets/sertif-1.png";
import sertif2 from "./assets/sertif-2.png";
import slideToggle from "./assets/slide-toggle.svg";
import smartphoneIcon from "./assets/smartphone_icon.png";
import stageIcon1 from "./assets/stage-icon 1.png";
import stageIcon2 from "./assets/stage-icon 2.png";
import stageIcon3 from "./assets/stage-icon 3.png";
import stageIcon4 from "./assets/stage-icon 4.png";
import telegramIcon from "./assets/telegram__icon.svg";
import whatrsappIcon from "./assets/whatsapp__icon.svg";
import workExampleIcon from "./assets/work_example_icon.png";
const hello = require("./js/hello");
